<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260526111349 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE rss_source_tag (rss_source_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (rss_source_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_D4E1BE37DAE23DB1 ON rss_source_tag (rss_source_id)');
        $this->addSql('CREATE INDEX IDX_D4E1BE37BAD26311 ON rss_source_tag (tag_id)');
        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(80) NOT NULL, slug VARCHAR(80) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_389B783989D9B62 ON tag (slug)');
        $this->addSql('ALTER TABLE rss_source_tag ADD CONSTRAINT FK_D4E1BE37DAE23DB1 FOREIGN KEY (rss_source_id) REFERENCES rss_source (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rss_source_tag ADD CONSTRAINT FK_D4E1BE37BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rss_source DROP category');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE rss_source_tag DROP CONSTRAINT FK_D4E1BE37DAE23DB1');
        $this->addSql('ALTER TABLE rss_source_tag DROP CONSTRAINT FK_D4E1BE37BAD26311');
        $this->addSql('DROP TABLE rss_source_tag');
        $this->addSql('DROP TABLE tag');
        $this->addSql('ALTER TABLE rss_source ADD category VARCHAR(100) DEFAULT NULL');
    }
}
