; Production : OPcache ne revérifie JAMAIS les fichiers (perfs maximales).
; Conséquence : pour déployer du nouveau code, il faut reconstruire l'image.
opcache.validate_timestamps = 0
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 20000
opcache.memory_consumption = 256
opcache.fast_shutdown = 1
